spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/OnlineSchool #Нужно указать вашу БД
    username: postgres # пользователь который указат у вас при создании БД
    password: passkey # пароль который указат у вас при создании БД
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  thymeleaf:
    cache: false

server:
  port: 8081
